### ISSUE TITLE
Intensive CPU

### ISSUE THREAD

**Issue by chrissimpson-unosquare** [akmolina28/last-watch-ai#40] opened 2021-02-01 09:43 UTC
Hi,

I am running Last Watch on Windows 10, Docker Desktop, 3.1.0.  I have the following as a config file for WSL 2:

[wsl2]
memory=3GB # Limits VM memory in WSL 2 to 4 GB
processors=5 # Makes the WSL 2 VM use two virtual processors

I noticed that it was consuming a lot of resources, specifically lw_watcher, at around 25% CPU.  It is also spawning a lot of effort through the COM Surrogate process, making total CPU up to 80%.  Is this expected?

![image](https://user-images.githubusercontent.com/49905236/106442657-701e9080-6473-11eb-82f2-f1cf5c3a3167.png)

On research, it appears there may be an issue with regard to the access of files within Windows outside of the Container.  This is known to cause problems although I am unsure how to resolve it.

Great product btw!  Many thanks for your efforts!

**Comment by akmolina28** [comment] 2021-02-01 13:20
That's unusual. The watcher is a [tiny node.js container](https://github.com/akmolina28/webhook-folder-watcher) which just watches for files and calls the webhook to kick off the detection. Most of the work is done by lw_queue and lw_deepstack. The watcher hovers between 1% and 1.5% on my dev machine machine.

Here is my .wslconfig...

```
[wsl2]
memory=4GB
processors=4
```

What I can say is that I didn't spend very much time developing the watcher, so there are probably some tweaks that could be made. And I think you are on the right track assuming it's an issue with the file system. In my experience, containers and VMs on Windows always have a hard time with the file system. Even on my Windows 10 Server box with tons of CPU and RAM, pages take a second or two to load because of latency with the file system.

One thing you can try right now is to enable polling in the .env file within Last Watch. It's a shot in the dark but it might help.

```
WATCH_USE_POLLING=true
```

If you are developer oriented feel free to tinker around with the source code for the watcher -- that's probably where I will start when I have some time. There are probably alternatives to chokidar that play better with Windows. 

Also note that the watcher container meant to be completely optional. You could build your own file watcher and have it call the same webhook in Last Watch... or you could even strip the watcher out of Last Watch and run the node.js app natively in Windows instead of WSL.

**Comment by akmolina28** [comment] 2021-02-02 22:29
I spent some more time looking at this today and I think it is happening when there are a lot of images in the watch folder. It also spikes the CPU if there are a lot of writes going on in the watch folder. I was able to reproduce this in windows and linux. I'm looking into more efficient ways to watch for new files.

**Comment by akmolina28** [comment] 2021-02-04 15:49
https://github.com/paulmillr/chokidar/issues/1057

It looks like this might be an issue with chokidar in Docker containers. I'm looking for other cross-platform solutions -- I tried python but it struggles with Windows volumes. 

Unfortunately chokidar might be the best cross-platform solution despite the performance issues. I still think the issue is manageable if you just keep your watch folder from growing too large. I only dedicate 2 cores (intel core-i5) and 2gb of memory and performance has never been an issue for me.

**Comment by depuits** [comment] 2021-02-15 12:22
Nice to see that the issue seems to be detected. I'll try and setup an instance with smaller folders. What solution are you using to keep the folder size down? You can't just delete all files or the event images are not displayed in the web interface. Maybe there could be a delete file if detection is negative?

**Comment by akmolina28** [comment] 2021-02-15 16:56
I am generating snapshots with Blue Iris which lets you limit the size of the folder and the maximum age of the snapshots. I have the upper limits set to 4GB or 7 days old. Last Watch also automatically deletes data older than 7 days by default, but it does not delete images from the watch folder.

**Comment by akmolina28** [comment] 2021-02-18 02:26
I am working on a new major release focused on performance which should fix these issues with the watcher. 

Currently the watcher is looking for new files in the watch folder and it sends the file path to the webhook.

In the new version, the watcher will post the actual image data to the webhook, and Last Watch will save the image in its public folder. After posting the image, the watcher will automatically delete the original image. This keeps the watch folder empty and dramatically improves performance. 

I am running a 4K camera and 2 HD cameras and here are my stats now on 2 cores and 2GB memory:

![image](https://user-images.githubusercontent.com/2997206/108295997-5614cb80-715e-11eb-8d1d-4bcfbf284564.png)

I am still testing it but I think it will be ready for a beta release within the next few days.

**Comment by akmolina28** [comment] 2021-02-23 19:23
@chrissimpson-unosquare @depuits there is a new beta release available that should help a lot with performance. https://github.com/akmolina28/last-watch-ai/releases/tag/1.0.0-beta.

Once the 1.0 version is stable and can move out of beta, I will close this issue.

**Comment by akmolina28** [comment] 2021-03-29 12:47
Fixed in the latest release

**Closed by akmolina28** 2021-03-29 12:47 UTC

**Comment by chrissimpson-unosquare** [comment] 2021-03-29 22:27
Awesome, thanks man!  I will try and see.  Great work!
