### ISSUE TITLE
Events come in with 12 hour delay

### ISSUE THREAD

**Issue by depuits** [akmolina28/last-watch-ai#8] opened 2020-12-02 18:06 UTC
Events and files come in with a huge delay. The detection itself is great, but because of the delay the events are useless. I've looked at the file watcher log and I can see the files being detected there after a second. 

The time used in the event is also off by this delay so it would say `25 minutes ago` for a file from almost a day ago.

I'm not sure what the next step is for looking where the delay comes from. If there are any more details that could help let me know.

**Comment by depuits** [comment] 2020-12-03 16:25
In the `webhook_calls` I can see that the delay is also visible there, the filename is the actual date:
```
'5893', 'default', '{\"file\":\"frontGate\\/2020-12-01\\/18-55-52.jpg\"}', NULL, '2020-12-03 13:43:25', '2020-12-03 13:43:25'
```
In the `failed_jobs` I also have some entries but not for every image. The error is always the following:
```
ErrorException: Undefined property: stdClass::$predictions in /var/www/app/app/DeepstackResult.php:21
Stack trace:
#0 /var/www/app/app/DeepstackResult.php(21): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined prope...', '/var/www/app/ap...', 21, Array)
#1 /var/www/app/app/Jobs/ProcessDetectionEventJob.php(56): App\DeepstackResult->getPredictions()
#2 [internal function]: App\Jobs\ProcessDetectionEventJob->handle(Object(App\DeepstackClient))
#3 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#4 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#5 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#6 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /var/www/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#9 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\ProcessDetectionEventJob))
#10 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessDetectionEventJob))
#11 /var/www/app/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(83): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\ProcessDetectionEventJob), false)
#13 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\ProcessDetectionEventJob))
#14 /var/www/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\ProcessDetectionEventJob))
#15 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(85): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(59): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\DatabaseJob), Object(App\Jobs\ProcessDetectionEventJob))
#17 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\DatabaseJob), Array)
#18 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Jobs\Job->fire()
#19 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(306): Illuminate\Queue\Worker->process('database', Object(Illuminate\Queue\Jobs\DatabaseJob), Object(Illuminate\Queue\WorkerOptions))
#20 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(132): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\DatabaseJob), 'database', Object(Illuminate\Queue\WorkerOptions))
#21 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon('database', 'default', Object(Illuminate\Queue\WorkerOptions))
#22 /var/www/app/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker('database', 'default')
#23 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#24 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array(Array, Array)
#25 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#26 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#27 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#28 /var/www/app/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#29 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call(Array)
#30 /var/www/app/vendor/symfony/console/Command/Command.php(258): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#31 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#32 /var/www/app/vendor/symfony/console/Application.php(916): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /var/www/app/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/app/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /var/www/app/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /var/www/app/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 {main}
```

**Comment by depuits** [comment] 2020-12-03 17:10
When I attach to the watcher container I see that files seem to be added in batches. Result logs also take a long while before they are printed and are not equivalent to the file added logs, which if I am correct should be a 1 to 1 log.

A small part of the watcher log as example:
```
file added: frontGate/2020-12-03/17-59-37.jpg
file added: frontGate/2020-12-03/17-59-38.jpg
file added: frontGate/2020-12-03/17-59-39.jpg
file added: frontGate/2020-12-03/17-59-40.jpg
file added: frontGate/2020-12-03/17-59-41.jpg
file added: frontGate/2020-12-03/17-59-42.jpg
file added: frontGate/2020-12-03/17-59-43.jpg
file added: frontGate/2020-12-03/17-59-44.jpg
result: [object Object]
file added: frontGate/2020-12-03/17-55-04.mp4.thumb
file added: frontGate/2020-12-03/17-59-45.jpg
file added: frontGate/2020-12-03/17-59-46.jpg
file added: frontGate/2020-12-03/17-59-48.jpg
file added: frontGate/2020-12-03/17-59-47.jpg
file added: frontGate/2020-12-03/17-59-49.jpg
file added: frontGate/2020-12-03/17-59-50.jpg
file added: frontGate/2020-12-03/17-59-52.jpg
```

I tried to do a fresh install but that results in the same delay.

**Comment by akmolina28** [comment] 2020-12-03 17:37
It looks like something is wrong with the file watcher. When a file is picked up, it should trigger a webhook call immediately and the response should be quick. Here is what my logs look like:

```
file added: annke101sd.20201203_111514623.jpg
result: [object Object]
file added: eufy102.20201203_111519042.jpg
result: [object Object]
file added: eufy102.20201203_111524072.jpg
result: [object Object]
file added: eufy102.20201203_111633486.jpg
result: [object Object]
file added: eufy102.20201203_111639246.jpg
result: [object Object]
file added: eufy102.20201203_111644285.jpg
result: [object Object]
file added: eufy102.20201203_111650132.jpg
result: [object Object]
file added: eufy102.20201203_111655147.jpg
result: [object Object]
file added: eufy102.20201203_111700219.jpg
result: [object Object]
file added: eufy102.20201203_111808140.jpg
result: [object Object]
file added: eufy102.20201203_111813215.jpg
result: [object Object]
file added: eufy102.20201203_111818239.jpg
result: [object Object]
file added: eufy102.20201203_111823335.jpg
result: [object Object]
file added: eufy102.20201203_111828392.jpg
result: [object Object]
file added: eufy102.20201203_111833454.jpg
result: [object Object]
file added: eufy102.20201203_111943049.jpg
result: [object Object]
file added: eufy102.20201203_111948166.jpg
result: [object Object]
file added: eufy102.20201203_111953254.jpg
result: [object Object]
file added: eufy102.20201203_111958290.jpg
result: [object Object]
```

Out of everything in this project, the file watcher was the least tested. I hacked it together in a few minutes in node.js, but I've never had any problems with it so I haven't gone back to clean it up.

https://github.com/akmolina28/webhook-folder-watcher

I would start by using a REST client to imitate what the file watcher does. I.e. take the path of an image file and post it manually to the webhook url. Hopefully the detection event will be generated and processed immediately, as expected. This would confirm that the problem is somewhere in the watcher. On the other hand if you still see slowness, then the problem is in somewhere the application.

**Comment by depuits** [comment] 2020-12-03 18:39
When calling the API directly it works and it shows up directly in the web interface. In the meantime I've managed to reproduce the delay on another computer. The images are being saved to a file server and accessed over SMB. So the combination of the SMB seems to be causing the delay. I've also tried using sshfs but that has the same result. Do you think that problem can be resolved or should the files be placed locally?

**Comment by akmolina28** [comment] 2020-12-03 23:06
In the short term, yes place the files locally. Can you set up the SMB share on the server that's running Last Watch and have your remote server push the images there instead? That's how I'm doing it.

In the long term, I plan to make the file watcher optional. That's why I broke it out into a separate container and set up the webhook listener. Right now you can only post the image *path* to the webhook but I want to be able to post the actual image file as well. 

There is probably something you could do to make the file watcher play better with SMB folders. Chokidar probably has polling or some other method that deals with this situation. I bet you could get it working. Or you could write your own tool to post the SMB file paths to the webhook.

**Comment by akmolina28** [comment] 2020-12-04 16:18
I just pushed some changes that might help you. There is a new variable in the .env file called `WATCH_USE_POLLING`. Setting this to true will use polling instead of the native fs, which should work better for mounted directories.

I tested by mounting an external SMB share and using that as my watch folder. It appears to be working as expected when polling is turned on.

You may have to manually pull the docker images to get the latest version of the file watcher. Roughly, here are the steps to upgrade:

1. Stop the containers and pull the latest from master

```
cd /path/to/last-watch-ai
sudo docker-compose down
git pull
```

2. Edit your .env file and add `WATCH_USE_POLLING=true`

```
nano .env
```

3. Pull the latest images and restart the containers

```
sudo docker-compose pull
sudo docker-compose up -d --build site
```

4. Check the watcher logs to see if the delay issue is fixed. Also check the output to make sure that the latest image is being used.

```
sudo docker logs --follow lw_watcher
```

Your output should look like this:

![image](https://user-images.githubusercontent.com/2997206/101186405-a88f2300-3618-11eb-9d29-2679d4318a2a.png)

**Comment by depuits** [comment] 2020-12-04 17:24
Thanks in the meantime I've changed my saving directory to a local drive. Another option might have been to run the file watcher on the SMB server and notify last watch by sending the web hook from there. But I will probably stick to the local drive for now. I'll test some more to see how the detection is going. 

For debugging it might be interesting to see the actual timestamp in the ui and the time at which the image recognition returned it's result. That way you could see in the ui if the one or the other is a bottleneck.

**Comment by depuits** [comment] 2020-12-07 16:59
So last night I had a lot of images because the motion detection got triggered by fog and rain. The files are now stored locally but it is again running behind around 10 or 12 hours. 

I can see the files coming in on the log of the `file watcher` and they appear in the `webhook_calls` table of the database (not always instant but within 30 seconds). But I can't see those files in the UI.

I am currently running 2 camera's (1920x1080 and 1280x720) on a vm which currently has 12gb ram and 16 cores.

After deleting all rows from the jobs list it is now adding files again to the UI and objects are being recognized, but the cpu keeps over 60%. With lots of `python3 /app/intelligencelayer/shared/detection.py`.

**Comment by akmolina28** [comment] 2020-12-07 20:25
Long post ahead but hopefully this will give you some ideas to troubleshoot.

I am running my ubuntu LXC container with only 2 cores and 2GB of ram and I have never had this problem. I am running 1 outdoor camera at 480p and two indoor cameras at 1080p and they generate thumbnails every 5 seconds. The detection is always sub 1 second, which I can confirm by comparing the created_at to the updated_at on the detection_events table (the deepstack_response column gets updated when the detection finishes). My vCPU (old gen core i5) gets pinged every time the detection runs but I never see it go above 40% or so. Average usage sits around 6%.

The fact that the jobs table is filling up is concerning. The queue container uses Supervisor to process jobs sequentially from that table, but it sounds like it can't keep up with the number of jobs coming in. You could try increasing the number of worker threads since you have 16 cores available (set NUMPROCS in the docker-compose.yml file and restart the containers). However more parallelism won't really help if the jobs are indeed taking 12 hours to finish.

The fact that you had weird delays with the watcher, and now you are having the *same* 12 hour delays with the queue, makes me wonder if the underlying issue is the same in both cases. It really sounds like it could be IO bound and makes me wonder how your image files are being stored. It also makes me wonder if this is a docker issue -- I really have no experience with Docker so it's hard for me to say.

My best guess is that step 6 is where you are getting stuck. See if you can rule out the other steps before step 6. Once we are sure that step 6 is the problem, I would suggest maybe adding some trace logging to the detection() function above. We might also want to break out the get_file_contents() call onto a separate line so we can rule that out as a source of slowness.

Assuming we can conclude that deepstack is taking 12 hours to respond, the next question is why. At this point I would suggest playing around with the deepstack API to see if you can reproduce the slowness without using Last Watch. As long as the containers are up the service should be available on port 5001 (visit localhost:5001 to see the landing page). For example,

```
curl -X POST -F image=@/path/to/image-file.jpg 'http://localhost:5001/v1/vision/detection'
```

should return JSON predictions almost immediately. See if it takes 12 hours when you hit the API manually with a bunch of image files from the same source folder. If deepstack is quick, that tells us that something about Last Watch or Docker is the problem.



All of that being said, somewhere in this process I think your jobs are getting stuck. Here is a full outline of the process with ways to check if that step is being completed:

1. The watcher sees a new file and posts the file *path* as a string to the webhook in laravel. You can see the 200 responses in the watcher logs to confirm that this step is completing quickly.

2. Laravel saves the webhook call to the database and dispatches a new webhook job which runs immediately. You can check for records in the webhook_calls table to see that this step is completing.

3. The webhook job reads the metadata of the image using the file path provided and creates a new detection event. You should see a row in detection_events when this step finishes.

4. Next, the webhook job checks if the image file matches any active profiles. If at least one profile matches the image file, a relationship is created in the pattern_match table and a detection job is dispatched into the jobs table. If no matching profiles are active, then the job is *not* dispatched and the process is complete.

5. Supervisor (running in the queue container) should pick up the new detection job immediately and the record in the jobs table will be deleted.

6. The detection job reads the image from the file system and will POST the image data to the deepstack API. 

```
    public function detection($image_path)
    {
        $url = $this->api_base_url . 'v1/vision/detection';

        $response = Http::attach(
            'image',
            file_get_contents($image_path),
            'photo.jpg'
        )->post($url);

        return $response->body();
    }
```

Note that the file is read in first, which is IO bound and could be getting blocked for some reason.

As soon as the deepstack API returns a result, the deeptack_response field in the detection_events record is updated. You can check this field and the updated_at timestamp to see when this is completing.

7. The detection job parses the response from the deepstack API and triggers all automations for the relevant objects. You should see records in the ai_predictions table and in the detection_event_automation_results table (assuming some automations were actually triggered).

**Comment by akmolina28** [comment] 2020-12-07 20:34
One more thought -- make sure deepstack is not running on "High" mode.

> Performance
>
> DeepStack offers three modes allowing you to tradeoff speed for peformance. During startup, you can specify performance mode to be , “High” , “Medium” and “Low”
>
> The default mode is “Medium”
>
> You can speciy a different mode as seen below
>
> sudo docker run -e MODE=High -e VISION-FACE=True -v localstorage:/datastore \
> -p 80:5000 deepquestai/deepstack
> Note the -e MODE=High above

I didn't specify a mode and it should run in Medium mode by default. You can explicitly specify by adding the environment variable to docker-compose,yml like this:

```
...
  deepstack:
    image: deepquestai/deepstack
    container_name: lw_deepstack
    restart: unless-stopped
    volumes:
      - localstorage:/datastore
    environment:
      - VISION-DETECTION=True
      - MODE=Medium
    networks:
      - laravel
    ports:
      - "5001:5000"
...
```

**Comment by depuits** [comment] 2020-12-09 07:35
Editing the docker-compose,yml didn't seem to change anything.

1.    The watcher sees a new file and posts the file path as a string to the webhook in laravel. You can see the 200 responses in the watcher logs to confirm that this step is completing quickly.
_Result logs are not always in order but they are all picked up within 5 seconds_

2.    Laravel saves the webhook call to the database and dispatches a new webhook job which runs immediately. You can check for records in the webhook_calls table to see that this step is completing.
_Webhook call are created directly after the webhook call from the file watcher so that seems fine_

|     id      |  name  |                           payload                                      | exception |        created_at          | updated_at |
|------------|----------|-----------------------------------------------------------------|--------------|-----------------------------|-----------------|
| 104197 | default | {\"file\":\"frontGate\\/2020-12-09\\/07-57-26.jpg\"} | NULL       | 2020-12-09 06:57:34| 2020-12-09 06:57:34 |

3.    The webhook job reads the metadata of the image using the file path provided and creates a new detection event. You should see a row in detection_events when this step finishes.
_So here seems to be the bottleneck. At time of writing the last entry here is from 23:44 yesterday._

| id | image_file_name | deepstack_response | created_at | updated_at | image_dimensions | occurred_at |
|----|------------------------|------------------------------|---------------|-----------------|---------------------------|-----------------|
| 74105 | events/frontGate/2020-12-08/23-44-14.jpg | | 2020-12-09 07:03:14 | 2020-12-09 07:03:14 | 1280x720 | 2020-12-09 07:03:14 |

4.    Next, the webhook job checks if the image file matches any active profiles. If at least one profile matches the image file, a relationship is created in the pattern_match table and a detection job is dispatched into the jobs table. If no matching profiles are active, then the job is not dispatched and the process is complete.
_I guess this is running correctly because the results come through eventually._

5.    Supervisor (running in the queue container) should pick up the new detection job immediately and the record in the jobs table will be deleted.
_Jobs are created but if to many images come in a backlog is created which in turn slow down the machine. There are currently 25593 entries in the jobs queue._

6.    The detection job reads the image from the file system and will POST the image data to the deepstack API.
_Calling the deepstack manually takes around 5 seconds to process so that is probably not helping when images might be send every second._

Currently I'm using motioneye to handle my camera's which will generate images every second when motion is detected. As you are only sending images every 5 seconds what would be a good way to limit the image throughput? The only thing I can currently come up with is using a regex and only process the images on second 0 and 5 but that doesn't really seem like a clean solution. I;ve now also set the deepstack to `Low` so we'll see what that does.

**Comment by akmolina28** [comment] 2020-12-15 17:15
Did you have any luck figuring this out?

FYI -- I pushed a new release to improve logging for the deepstack API. Now in the UI you can view all of the deepstack API logs and see the run-time.

**Comment by depuits** [comment] 2020-12-15 17:29
Not yet, I've seen your changes and update when I have some time. Hopefully it helps to pinpoint the problem some more.

**Comment by jaycrossler** [comment] 2020-12-20 21:02
Not too much to add - just a post that I'm not having any delays in images/processing.  I've only got 4 cameras now, and will increase and let you know if I can replicate the issue.

**Comment by akmolina28** [comment] 2020-12-21 04:13
@jaycrossler thanks for the input. Good to know other people are having success.

**Comment by akmolina28** [comment] 2021-03-29 12:48
Fixed in the latest release

**Closed by akmolina28** 2021-03-29 12:48 UTC
